# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 108f71e6b927be9924fe9662496493a406393740fac491b702cd3b5bcc8b9214a5033fae7549d0f40d00ae91e501dfd4e0672638aa554955b1d2099612410e1e

test:
  secret_key_base: 190e243dc64cd32c292832758110f0fc9390513ea2c052a4ff1d6b5087dcd397c8f35b6d09c1724c375ef368d9670ef5f58fe64e6e8a0e81993bac713287f4db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
